/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd8b


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TurtlesRuntimeModule extends AbstractTurtlesRuntimeModule {
}
