/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.mdd8b


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TurtlesStandaloneSetup extends TurtlesStandaloneSetupGenerated {

	def static void doSetup() {
		new TurtlesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
