/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.mdd8b.validation

import org.eclipse.emf.common.util.EList
import org.eclipse.xtext.validation.Check
import uk.ac.kcl.inf.mdd8b.turtles.*


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TurtlesValidator extends AbstractTurtlesValidator {

}
